apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namespace: default

patches:
- target:
    kind: Deployment
    name: nginx-deploymentk
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: nginx-deploymentk
    spec:
      replicas: 1
